/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElM: typeof import('element-plus/es').ElM
  const ElMes: typeof import('element-plus/es').ElMes
  const ElMess: typeof import('element-plus/es').ElMess
  const ElMessa: typeof import('element-plus/es').ElMessa
}
